package com.model;

/**
 * TZhuanjia generated by MyEclipse Persistence Tools
 */

public class TZhuanjia implements java.io.Serializable
{

	private final String serialVersionUID = "336159560511730739";
	
	private Integer id;

	private String xingming;
	private String xingbie;
	private Integer nianling;

	private Integer keshiId;
	private String shanchang;
	private String fujian;
	
	private String loginname;
	private String loginpw;
	private String del;
	
	private Integer userId;

	private TKeshi keshi;

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getXingming() {
		return xingming;
	}

	public void setXingming(String xingming) {
		this.xingming = xingming;
	}

	public String getXingbie() {
		return xingbie;
	}

	public void setXingbie(String xingbie) {
		this.xingbie = xingbie;
	}

	public Integer getNianling() {
		return nianling;
	}

	public void setNianling(Integer nianling) {
		this.nianling = nianling;
	}

	public Integer getKeshiId() {
		return keshiId;
	}

	public void setKeshiId(Integer keshiId) {
		this.keshiId = keshiId;
	}

	public String getShanchang() {
		return shanchang;
	}

	public void setShanchang(String shanchang) {
		this.shanchang = shanchang;
	}

	public String getFujian() {
		return fujian;
	}

	public void setFujian(String fujian) {
		this.fujian = fujian;
	}

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getLoginpw() {
		return loginpw;
	}

	public void setLoginpw(String loginpw) {
		this.loginpw = loginpw;
	}

	public String getDel() {
		return del;
	}

	public void setDel(String del) {
		this.del = del;
	}

	public TKeshi getKeshi() {
		return keshi;
	}

	public void setKeshi(TKeshi keshi) {
		this.keshi = keshi;
	}
	

}